#!/bin/bash
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

autorandr -c

export XDG_SESSION_TYPE=x11

. /etc/X11/xinit/xinitrc.d/50-systemd-user.sh

systemctl --user import-environment SSH_AGENT_PID SSH_AUTH_SOCK
systemctl --user restart dumpwatch

exec i3 -c "$XDG_CONFIG_HOME"/i3/config
