#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/"$UID"/dbus/user_bus_socket
exec i3 -c /home/kyrias/.config/i3/config
