set shortmess+=I


" Respect XDG
set viminfo+=n$XDG_CACHE_HOME/vim/viminfo
set directory=$XDG_CACHE_HOME/vim/swap,/tmp
set backupdir=$XDG_CACHE_HOME/vim/backup,/tmp
set undodir=$XDG_CACHE_HOME/vim/undo,/tmp
set runtimepath=$XDG_CONFIG_HOME/vim,$XDG_CONFIG_HOME/vim/after,$VIM,$VIMRUNTIME,/usr/share/vim/vimfiles
let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc"

" Make backspace behave in a sane manner.
set backspace=indent,eol,start

" NeoBndle stuff
set runtimepath+=~/.config/vim/bundle/neobundle.vim/
call neobundle#rc("$XDG_CONFIG_HOME/vim/bundle")
NeoBundleFetch 'Shougo/neobundle.vim'

NeoBundle 'Shougo/vimproc', {
 \ 'build' : {
 \     'unix' : 'make -f make_unix.mak',
 \     'mac' : 'make -f make_mac.mak',
 \    },
 \ }
NeoBundle 'Shougo/unite.vim'

" Colorscheme❤
NeoBundle "daylerees/colour-schemes", { "rtp": "vim-themes/" }
colorscheme Darkcustomside

NeoBundle 'mattn/emmet-vim'

NeoBundle 'miekg/rfc'

NeoBundle 'tommcdo/vim-exchange'

syntax on
filetype plugin indent on
set autoindent    " always set autoindenting on
set copyindent    " copy the previous indentation on autoindenting
set number        " always show line numbers
set smartcase     " ignore case if search pattern is all lowercase,
                  "    case-sensitive otherwise
set hlsearch      " highlight search terms
set incsearch     " show search matches as you type
set history=1000         " remember more commands and search history
set undolevels=1000      " use many muchos levels of undo
set wildignore=*.swp,*.bak,*.pyc,*.class
set title                " change the terminal's title
set visualbell           " don't beep
set noerrorbells         " don't beep
set ruler
set backup
set undofile                " Save undo's after file closes
set mouse=a
nnoremap ; :

map <up> <nop>
map <down> <nop>
map <left> <nop>
map <right> <nop>

nmap <silent> <Leader>/ :nohlsearch<CR>

cmap w!! w !sudo tee % >/dev/null

" Tabs are 4 spaces wide
set tabstop=4
set softtabstop=4
set shiftwidth=4
set noexpandtab

" voodoo magic
set hidden

" Paste mode when pressing Insert, disables autoformating
set pastetoggle=<Insert>

" Installation check.
NeoBundleCheck

set listchars=tab:»·,trail:·
set list

highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/
autocmd BufWinLeave * call clearmatches()

highlight Comment cterm=italic
