" Respect XDG
set viminfo+=n$XDG_CACHE_HOME/vim/viminfo
set directory=$XDG_CACHE_HOME/vim/swap,/tmp
set backupdir=$XDG_CACHE_HOME/vim/backup,/tmp
set undodir=$XDG_CACHE_HOME/vim/undo,/tmp
set runtimepath=$XDG_CONFIG_HOME/vim,$VIM,$VIMRUNTIME,/usr/share/vim/vimfiles,$XDG_CONFIG_HOME/vim/after

" NeoBundle stuff
set runtimepath+=$XDG_CONFIG_HOME/vim/bundle/neobundle.vim/
call neobundle#begin(expand('$XDG_CONFIG_HOME/vim/bundle'))
NeoBundleFetch 'Shougo/neobundle.vim'

NeoBundle 'Shougo/vimproc', {
 \ 'build' : {
 \     'unix' : 'make -f make_unix.mak',
 \     'mac'  : 'make -f make_mac.mak',
 \    },
 \ }
NeoBundle 'Shougo/unite.vim'
NeoBundle 'mattn/emmet-vim'
NeoBundle 'miekg/rfc'
NeoBundle 'tommcdo/vim-exchange'

call neobundle#end()

" Colorscheme
colorscheme Darkcustomside

" Allow backspacing over everything in insert mode
set backspace=indent,eol,start

syntax on
filetype plugin indent on
set autoindent
set copyindent
set number            " always show line numbers
set smartcase         " ignore case if search pattern is all lowercase,
                      "   case-sensitive otherwise
set hlsearch          " highlight search terms
set incsearch         " show search matches as you type
set history=1000
set undolevels=1000
set wildignore=*.swp,*.bak,*.pyc,*.o
set title             " change the terminal's title
set visualbell        " don't beep
set noerrorbells      " don't beep
set ruler
set backup            " use backup files
set undofile          " save undo's after file closes
set mouse=a           " enable mouse in all modes
set shortmess+=I      " don't show the nag-screen
set encoding=utf-8    " oh please, like this needs explanation
set showcmd

" Use space as a leader
map <space> <Leader>
nmap <silent> <Leader>/ :nohlsearch<CR>

cmap w!! w !sudo tee % >/dev/null

" Tabs are 4 spaces wide
set tabstop=4
set shiftwidth=4
set softtabstop=4
set noexpandtab

" Automatically hide buffers instead of requiring bangcommands
set hidden

" Paste mode when pressing Insert, disables autoformating
set pastetoggle=<Insert>

" Installation check.
NeoBundleCheck

set listchars=tab:»·,trail:·
set list

highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/
autocmd BufWinLeave * call clearmatches()

highlight Comment cterm=italic
