#!/usr/bin/env bash
#
# $1 Thread ID to toggle tag on

if [[ "$(notmuch search thread:$1 and tag:Spam)" ]]; then
	printf "unsetting tag Spam on thread %s\n" "$1"
	notmuch tag -Spam thread:"$1"
else
	printf "setting tag Spam on thread %s\n" "$1"
	notmuch tag +Spam thread:"$1"
fi
