#!/usr/bin/env bash
#
# $1 Message ID to toggle tag on

if [[ "$(notmuch search id:$1 and tag:Spam)" ]]; then
	printf "unsetting tag Spam on message %s\n" "$1"
	notmuch tag -Spam id:"$1"
else
	printf "setting tag Spam on message %s\n" "$1"
	notmuch tag +Spam id:"$1"
fi
