path=( "$HOME"/.local/bin
       "$HOME"/bin
       "$HOME"/.cargo/bin
       "$HOME"/.gem/ruby/2.1.0/bin
       "${path[@]}" )

# Set XDG Basedir Spec paths
export XDG_CACHE_HOME="$HOME"/.cache
export XDG_CONFIG_HOME="$HOME"/.config
export XDG_DATA_HOME="$HOME"/.local/share
if [[ -z "$XDG_RUNTIME_DIR" ]] && [[ -d /run/user/"$UID" ]] && [[ -w /run/user/"$UID" ]]; then
	export XDG_RUNTIME_DIR=/run/user/"$UID"
fi

# Program homedir overrides
export MPV_HOME="$XDG_CONFIG_HOME"/mpv
export GNUPGHOME="$XDG_CONFIG_HOME"/gnupg
export GALE_DIR="$XDG_CONFIG_HOME"/gale
export HTTPIE_CONFIG_DIR="$XDG_CONFIG_HOME"/httpie
export PASSWORD_STORE_DIR="$XDG_DATA_HOME"/password-store

# Config overrides
export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc-2.0
export XCOMPOSEFILE="$XDG_CONFIG_HOME"/X11/XCompose
export XAUTHORITY="$XDG_RUNTIME_DIR"/xauthority
export ABSROOT="$HOME"/build/abs

export VISUAL=nvim
export EDITOR=nvim

export BROWSER=chromium
export TERMINAL=termite

export PAGER=less
export LESS=-R
export LESSHISTFILE="$XDG_CACHE_HOME"/lesshist

export SDL_AUDIODRIVER=pulse

export SUDO_PROMPT=$'\e[31mSUDO\e[m password for \e[34m%p\e[m: '

export SHORTHOST=$(hostname -s)

# Don’t use the default venv prompt in favor of our custom one
export VIRTUAL_ENV_DISABLE_PROMPT=1

export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx

# LS_COLORS is now required for `ls` to use colors
source <(dircolors -b "$XDG_CONFIG_HOME"/dircolors)

if [[ -f "$ZDOTDIR"/profile.d/"$SHORTHOST" ]]; then
	source "$ZDOTDIR"/profile.d/"$SHORTHOST"
fi

if [[ -z $DISPLAY && $XDG_VTNR -eq 1 ]]; then
	exec startx "$XDG_CONFIG_HOME"/X11/xinitrc -- -keeptty -configdir "$XDG_CONFIG_HOME"/X11/xorg.conf.d
fi

# vim: set ft=zsh:
